### ISSUE TITLE
Classifying Laws for Simplifier

### ISSUE THREAD

**Issue by andrewbutterfield** [andrewbutterfield/reasonEq#3]
- [ ] Create new law classifier module `Classifier.lhs`
- [ ] Create new law classifier record datatype
        -  Idea: each class has a list of laws (by name)  in that class, possibly paired with extra stuff
         - Added as a new field to Theory data-type
         - Simplifier class is list of   law names paired with law direction
 - [ ] Add record to Theory datatype
 - [ ] Add `classify` command to top-level REPL
        - adds some function to `AbstractUI` - use `demoteLaw` as a template
        - it will call a function in `Theories` that has type signature `MonadFail m => Theory -> m Theory`
        - that will call a classifier function inside Classifier supplying list of `Laws` and classifier record,which returns modified classifier record

**Comment by saqzari** [comment]
Hello, I managed to add as much as possible on the auto branch. Would it be possible to get some feedback on what it looks like so far?

**Comment by andrewbutterfield** [comment]
Ok, re-sync with main (commit [6afc255]) and work on classifying and adding simplifiers.

I will create an issue for myself to setup the saving and restoring of auto-laws.

**Comment by saqzari** [comment]
Hello, for the current task of adding simplifiers, does that involve taking in a term value and converting that into a string?

**Comment by andrewbutterfield** [comment]
No, you use the *name* of the law from which the term comes.

**Comment by saqzari** [comment]
Hello, how would you get both sides of a law equation, I separated a term from the law but don't know what part of the equation it represents?

**Comment by andrewbutterfield** [comment]
It is the whole equation. You have to pattern match it so see if it has the form P ≡ Q.

That will be a Cons (C) with Identifier “equiv” and exactly two sub-terms in its list.

Basic pattern for a Cons term:   `Cons tk sb n ts`

There is a pattern for Predicate terms:  `PCons sb n ts` that assumes `tk` has value `P`.


--------------------------------------------------------------------
Andrew Butterfield     Tel: +353-1-896-2517     Fax: +353-1-677-2204
***@***.***, Head of Software Foundations & Verification Research Group
School of Computer Science and Statistics,
Room G.39, O'Reilly Institute, Trinity College, University of Dublin
                         http://www.scss.tcd.ie/Andrew.Butterfield/
--------------------------------------------------------------------




From: saqzari ***@***.***>
Reply to: andrewbutterfield/reasonEq ***@***.***>
Date: Tuesday 28 February 2023 at 18:09
To: andrewbutterfield/reasonEq ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [andrewbutterfield/reasonEq] Classifying Laws for Simplifier (Issue #3)


Hello, how would you get both sides of a law equation, I separated a term from the law but don't know what part of the equation it represents?

**Comment by andrewbutterfield** [comment]
We can close this issue - you can classify simplifiers. Next issue - using them
